Fix dirname for MacOSX.

diff --git a/various/mussync-tools b/various/mussync-tools
--- a/various/mussync-tools
+++ b/various/mussync-tools
@@ -12,7 +12,7 @@
 #  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
 #  ;login: The USENIX Magazine, February 2011:42-47.
 #
-version="1.4.5"
+version="1.4.6"
 
 
 
@@ -37,7 +37,7 @@ function basename() {
 
   return ${?}
 } # basename()
-
+export -f 'basename'
 
 
 script_name="$(basename "${0}")"
@@ -100,6 +100,30 @@ Usage :
   [[ -n "${1}" ]] && exit ${1}
 } # usage
 
+
+
+# Get the dirname of a path (multi-plateform version)
+# Print the result on &1 if found.
+#
+# @param string $path A path.
+#
+# @return A return code..
+function dirname() {
+
+  [[ ${#} -eq 0 ]] && exit 1
+
+  case "$(uname)" in
+    'Linux' )
+      command dirname -z -- "${@}"
+      ;;
+    'Darwin' | * )
+      command dirname -- "${@}"
+      ;;
+  esac
+
+  return ${?}
+} # dirname()
+export -f 'dirname'
 
 
 # Get the absolute path for a file or directory.
@@ -784,7 +808,7 @@ function convert_file() {
   local input_file="${1}"
 
   ## Build output file path based on input file path.
-  local input_file_path="$(dirname -z -- "${input_file}")"
+  local input_file_path="$(dirname "${input_file}")"
   local output_file_path="$(echo -n "${input_file_path}" | sed -e "s|^${input_path}|${output_path}|")"
   local short_path="$(echo -n "${input_file_path}" | sed -e "s|^${input_path}/||")"
 
@@ -1216,7 +1240,7 @@ function sync_delete_album()
       | while read -r -d '' 'output_file'; do
 
       ## Build input file path based on output file path.
-      local output_file_path="$(dirname -z -- "${output_file}")"
+      local output_file_path="$(dirname "${output_file}")"
       local input_file_path="$(echo -n "${output_file_path}" | sed -e "s|^${output_path}|${input_path}|")"
       local short_path="$(echo -n "${output_file_path}" | sed -e "s|^${output_path}||")"
 
